version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get upgrade -y
      - >
        apt-get install -y
        nasm
        libudev-dev
        gcc-5
        g++-5
        libmad0-dev
        libgtk2.0-dev
        binutils-dev
        libasound-dev
        libpulse-dev
        libjack-dev
        libc6-dev
        libogg-dev
        libvorbis-dev
        libxtst-dev
        libxrandr-dev
        libglew-dev
        libuv-dev
        clang-format-5.0
        libcurl4-openssl-dev
      - $CODEBUILD_SRC_DIR/.ci/build.sh
  pre_build:
    commands:
      - mkdir -p $CODEBUILD_SRC_DIR/build
      - cd $CODEBUILD_SRC_DIR/build
      - cmake ..
  build:
    commands:
      - make -j 4
